//Copyright (c) 2024 Hollow World Games All Rights Reserved
#pragma once
#include "NativeGameplayTags.h"


EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ShirtTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PantsTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BootsTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BackTag);

EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HelmetTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ChestTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ShouldersTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BracerTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GloveTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LegArmorTag);


EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MainScabardTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(OffHandScabardTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BackScabardTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MainHandTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(OffHandTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RangedTag);
EQUIPMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SideQuiverTag);