#pragma once

#include "NativeGameplayTags.h"

GAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ImpactEventTag);
GAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MissEventTag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponTag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(MeleeWeaponTag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(RangedWeaponTag);
